In [ ]:
# Predict Horse or Human
 
Here we are loading train CNN model to predict Given input (image) is Horse of Human
 
# Import Libraries

# Predict Horse or Human
 
Here we are loading train CNN model to predict Given input (image) is Horse of Human
 
# Import Libraries

In [1]:
import numpy as np
 
import keras 
from keras.preprocessing.image import ImageDataGenerator

 Import Model

In [39]:
model_path1 = 'C:\\Users\\ASUS\\DEEP Learning Project\\Horse or Human classification using cnn\\horse_or_human_predictor.h5' #new model.ipynb
model_path2 = 'C:\\Users\\ASUS\\DEEP Learning Project\\Horse or Human classification using cnn\\horse_or_human_predictor_v1.h5' #v2 solve overfitting Horse_or_human Classification using CNN.ipynb
#model_path3 = 'C:\\Users\\ASUS\\DEEP Learning Project\\Horse or Human classification using cnn\\horse_human_cnn_model_v2_1.h5' #v2 solve overfitting Horse_or_human Classification using CNN.ipynb

In [40]:
model1 = keras.models.load_model(model_path1)
model2 = keras.models.load_model(model_path2)


Preprocessing

horse image path

In [41]:
h1='C:\\Users\\ASUS\\DEEP Learning Project\\Horse or Human classification using cnn\\horse& human test data\\h1.jpg'
h2='C:\\Users\\ASUS\\DEEP Learning Project\\Horse or Human classification using cnn\\horse& human test data\\h2.jpg'
h3='C:\\Users\\ASUS\\DEEP Learning Project\\Horse or Human classification using cnn\\horse& human test data\\h3.jpg'
h4='C:\\Users\\ASUS\\DEEP Learning Project\\Horse or Human classification using cnn\\horse& human test data\\h4.jpg'
h5='C:\\Users\\ASUS\\DEEP Learning Project\\Horse or Human classification using cnn\\horse& human test data\\h5.jpg'

Human image path


In [42]:
hum1='C:\\Users\\ASUS\\DEEP Learning Project\\Horse or Human classification using cnn\\horse& human test data\\hum1.jpg'
hum2='C:\\Users\\ASUS\\DEEP Learning Project\\Horse or Human classification using cnn\\horse& human test data\\hum2.jpg'
hum3='C:\\Users\\ASUS\\DEEP Learning Project\\Horse or Human classification using cnn\\horse& human test data\\hum3.jpg'
hum4='C:\\Users\\ASUS\\DEEP Learning Project\\Horse or Human classification using cnn\\horse& human test data\\hum4.jpg'
hum5='C:\\Users\\ASUS\\DEEP Learning Project\\Horse or Human classification using cnn\\horse& human test data\\hum5.jpg'
hum6='C:\\Users\\ASUS\\DEEP Learning Project\\Horse or Human classification using cnn\\horse& human test data\\hum6.jpg'

In [43]:
import numpy as np
from keras.preprocessing import image

In [44]:
def pred_human_horse(model, horse_or_human):
  test_image = image.load_img(horse_or_human, target_size = (150, 150))
  test_image = image.img_to_array(test_image)/255
  test_image = np.expand_dims(test_image, axis = 0)

  result = model.predict(test_image).round(3)
  pred = np.argmax(result)
  print(result, "--->>>", pred)
 
  if pred == 0:
    print('Predicted>>> Horse')
  else:
    print('Predicted>>> Human')

In [45]:
"""## Predict Output"""
 
for horse_or_human in [h1,h2,h3,h4,h5, hum1,hum2,hum3,hum4,hum5,hum6]:
  pred_human_horse(model2, horse_or_human)

1/1 [==============================] - 1s 820ms/step
[[0.972 0.028]] --->>> 0
Predicted>>> Horse
1/1 [==============================] - 0s 90ms/step
[[0.743 0.257]] --->>> 0
Predicted>>> Horse
1/1 [==============================] - 0s 116ms/step
[[0. 1.]] --->>> 1
Predicted>>> Human
1/1 [==============================] - 0s 39ms/step
[[0.791 0.209]] --->>> 0
Predicted>>> Horse
1/1 [==============================] - 0s 36ms/step
[[0. 1.]] --->>> 1
Predicted>>> Human
1/1 [==============================] - 0s 41ms/step
[[0. 1.]] --->>> 1
Predicted>>> Human
1/1 [==============================] - 0s 252ms/step
[[0. 1.]] --->>> 1
Predicted>>> Human
1/1 [==============================] - 0s 294ms/step
[[0.405 0.595]] --->>> 1
Predicted>>> Human
1/1 [==============================] - 0s 375ms/step
[[0.901 0.099]] --->>> 0
Predicted>>> Horse
1/1 [==============================] - 0s 101ms/step
[[0.007 0.993]] --->>> 1
Predicted>>> Human
1/1 [==============================] - 0s 112ms/step
[[0.7